#include "direction.h"

void directions_initialise() {
	// -1 on X (West)
	DIRECTIONS[DIRECTION_NW].x = DIRECTIONS[DIRECTION_W].x = DIRECTIONS[DIRECTION_SW].x = -1;
	//  0 on X (neutral)
	DIRECTIONS[DIRECTION_N].x  = DIRECTIONS[DIRECTION_0].x = DIRECTIONS[DIRECTION_S].x  =  0;
	// +1 on X (East)
	DIRECTIONS[DIRECTION_NE].x = DIRECTIONS[DIRECTION_E].x = DIRECTIONS[DIRECTION_SE].x = +1;

	// -1 on Y (North)
	DIRECTIONS[DIRECTION_NW].y = DIRECTIONS[DIRECTION_N].y = DIRECTIONS[DIRECTION_NE].y = -1;
	//  0 on Y (neutral)
	DIRECTIONS[DIRECTION_W].y  = DIRECTIONS[DIRECTION_0].y = DIRECTIONS[DIRECTION_E].y  =  0;
	// +1 on Y (South)
	DIRECTIONS[DIRECTION_SW].y = DIRECTIONS[DIRECTION_S].y = DIRECTIONS[DIRECTION_SE].y = +1;
}
