#ifndef DIRECTION_H
#define	DIRECTION_H

const unsigned short
DIRECTION_NW,	DIRECTION_N, DIRECTION_NE,
DIRECTION_W,	DIRECTION_0, DIRECTION_E,
DIRECTION_SW,	DIRECTION_S, DIRECTION_SE;

short
	DIRECTION_AXIS_X[9],
	DIRECTION_AXIS_Y[9];


#endif	/* INPUT_H */

